1. “만나서 반갑습니다” 를 출력하세요

In [ ]:
print("만나서 반갑습니다")

만나서 반갑습니다

2. word1 = “파이썬”
   word2 = “ 재미있게 즐겨봅시다”

 위의 2개의 변수를 이용하여
”파이썬 재미있게 즐겨봅시다”  프린트하기

In [ ]:
word1 = "파이썬"
word2 = " 재미있게 즐겨봅시다"

print(word1 + word2)

파이썬 재미있게 즐겨봅시다

3. 변수 'word1'의 데이터타입(data type)을 출력하세요

In [ ]:
word1 = "파이썬"
word2 = " 재미있게 즐겨봅시다"

print(type(word1))

<class 'str'>

4. classroom = “Kairos 401”
위 변수에서 “401”만 출력해주세요

In [ ]:
classroom = "Kairos 401"

print(classroom[-3:])

401

[영화]
movie
main_actors
나의 아저씨
이선균
서울의 봄
정우성
5.  위 테이블의 영화와 주연 배우를 이용하여 2개의 리스트(movies, main_actors) 만들고 출력하세요

In [ ]:
movie = ["나의 아저씨", "서울의 봄"]
main_actors = ["이선균", "정우성"]

print(list[movie, main_actors])

list[['나의 아저씨', '서울의 봄'], ['이선균', '정우성']]

============================================

6. 5번에서 만든 2개의 리스트를 이용하여 1개위 튜플(movies_tuple) 리스트를 만들고 출력하세요
(예: movies_tuple = [(”나의 아저씨”, “이선균”), (”서울의봄”, “정우성”)]

7. 위 튜플 리스트를 이용해서 딕셔너리(movies_dict)을 만들고 출력하세요

8. 주사위를 10000번돌린다고 가정하고 각 랜덤 번호마다 빈도를 딕셔너리로 정리하고 matplotlib를 이용하여 시각화해주세요

9. 위의 코드를 함수(function)로 만들어주세요 (자유형식)

10. data_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) 에서 2번째 행을 출력하세